### Default variable file for lms-service ###

namespace: dev
imagepullsecrets: devregistrysecret
dockerhub: eagle-docker.tarento.com


env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: sb-cb-ext-service
image_tag: af25575
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 7001
  targetport: 7001
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

