### Default variable file for lms-service ###

namespace: dev
imagepullsecrets: devregistrysecret
dockerhub: eagle-docker.tarento.com


env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: vega-rasa-server
image_tag: bronze
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 80
  targetport: 5005
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

ui_proxies_bulk_upload: /mydata/bulk_upload


