### Default variable file for lms-service ###

namespace: dev
imagepullsecrets: devregistrysecret
dockerhub: eagle-docker.tarento.com


env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: pm-zuul-service
image_tag: f2f51c7
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8080
  targetport: 8080
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

