import { Node, Edge } from 'vis-network'
import { IDynamicDataContent } from '../../dynamic-network/models/dynamicNetwork.model'

export const dynamicData: {
  [key: string]: { nodes?: Node[]; edges?: Edge[]; opened?: boolean }[];
} = {
  lex_auth_01285522270547148814: [
    {
      nodes: [
        {
          id: 0,
          label: 'Digitalization',
                 // title: 'Digitalization',
          group: 'center',
          shape: 'circularImage',
          image:
                   '/assets/common/learning-path/tablet-mobile-communication_iStock-1079974870_1-col-entry.jpg',
          color: 'gray',
          size: 50,
        },
        {
          id: 1,
          label: 'Digi General',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/1.jpg',
          size: 40,
        },
        {
          id: 2,
          label: 'Digital Technologies',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/2.png',
          size: 40,
        },
        {
          id: 3,
          label: 'New Work',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/3.png',
          size: 40,
        },
        {
          id: 4,
          label: 'Digital Management',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/11.png',
          size: 40,
        },
        {
          id: 5,
          label: 'Digital Business',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/12.png',
          size: 40,
        },
      ],
      edges: [
               { from: 0, to: 1 },
               { from: 0, to: 2 },
               { from: 0, to: 3 },
               { from: 0, to: 4 },
               { from: 0, to: 5 },
      ],
      opened: true,
    },
    {
      nodes: [
        {
          id: 1,
          label: 'Digi General',
          group: 'first',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 15,
          label: 'Industry 4.0',
          group: 'digiGen',
        },
        {
          id: 16,
          label: 'Info\nDigitalization\n@Siemens',
          group: 'digiGen',
        },
        {
          id: 17,
          label: 'Digital\nReadiness\nCheck',
          group: 'digiGen',
        },
        {
          id: 18,
          label: 'Virtual\nCollaboration',
          group: 'digiGen',
        },
        {
          id: 19,
          label: 'Applying\nDigitalization\nto our Business ',
          group: 'digiGen',
        },
        {
          id: 20,
          label: 'Digi\nEvents',
          group: 'digiGen',
        },
      ],
      edges: [
               { from: 1, to: 15 },
               { from: 1, to: 16 },
               { from: 1, to: 17 },
               { from: 1, to: 18 },
               { from: 1, to: 19 },
               { from: 1, to: 20 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 2,
          label: 'Digital Technologies',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/2.png',
          size: 40,
        },
        {
          id: 6,
          label: 'Data Analytics\nand Artificial\nIntelligence',
          group: 'digiTek',
        },
        {
          id: 7,
          label: 'Architecture',
          group: 'digiTek',
        },
        {
          id: 8,
          label: 'Digital Twin',
          group: 'digiTek',
        },
        {
          id: 9,
          label: 'Future of\nAutomation',
          group: 'digiTek',
        },
        {
          id: 10,
          label: 'Product and\nSolution\nSecurity',
          group: 'digiTek',
        },
        {
          id: 11,
          label: 'Cloud / Edge /\nFog Computing',
          group: 'digiTek',
        },
        {
          id: 12,
          label: 'Digital\nEnterprise',
          group: 'digiTek',
        },
        {
          id: 13,
          label: 'Company Core\nTechnologies',
          group: 'digiTek',
        },
        {
          id: 14,
          label: 'Pluralsight',
          group: 'digiTek',
        },
      ],
      edges: [
               { from: 2, to: 6 },
               { from: 2, to: 7 },
               { from: 2, to: 8 },
               { from: 2, to: 9 },
               { from: 2, to: 10 },
               { from: 2, to: 11 },
               { from: 2, to: 12 },
               { from: 2, to: 13 },
               { from: 2, to: 14 },
      ],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 4,
          label: 'Digital Management',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/11.png',
          size: 40,
        },
        {
          id: 45,
          label: 'Are You\nPrepared?\n(Self-Reflection)',
          group: 'digiMgm',
        },
        {
          id: 46,
          label: 'Coaching\nAgile Teams ',
          group: 'digiMgm',
        },
        {
          id: 47,
          label: 'Entrepreneurial\nSkills',
          group: 'digiMgm',
        },
        {
          id: 48,
          label: 'Coordinating\nEcosystems',
          group: 'digiMgm',
        },
        {
          id: 49,
          label: 'Scouting\nTalent',
          group: 'digiMgm',
        },
        {
          id: 50,
          label: 'Driving\nCulture',
          group: 'digiMgm',
        },
        {
          id: 51,
          label: 'Translating\nVision',
          group: 'digiMgm',
        },
      ],
      edges: [
               { from: 4, to: 45 },
               { from: 4, to: 46 },
               { from: 4, to: 47 },
               { from: 4, to: 48 },
               { from: 4, to: 49 },
               { from: 4, to: 50 },
               { from: 4, to: 51 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 5,
          label: 'Digital Business',
          group: 'first',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/12.png',
        },
        {
          id: 21,
          label: 'Customer\nValue\nCo-Creation',
          group: 'digiBui',
        },
        {
          id: 22,
          label: 'Social\nSelling',
          group: 'digiBui',
        },
        {
          id: 23,
          label: 'Cyber\nSecurity',
          group: 'digiBui',
        },
        {
          id: 24,
          label: 'Leading your\nDigital\nBusiness\nTransformation',
          group: 'digiBui',
        },
        {
          id: 25,
          label: 'Digi\nFinance',
          group: 'digiBui',
        },
        {
          id: 26,
          label: 'Business\nModel\nInnovation',
          group: 'digiBui',
        },
      ],
      edges: [
               { from: 5, to: 21 },
               { from: 5, to: 22 },
               { from: 5, to: 23 },
               { from: 5, to: 24 },
               { from: 5, to: 25 },
               { from: 5, to: 26 },
      ],
      opened: false,
    },
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
    {
      nodes: [
        {
          id: 21,
          label: 'Customer\nValue\nCo-Creation',
          group: 'second',
          size: 35,
        },
        {
          id: 27,
          label: 'Landing Page\nCVCC - LFW',
          group: 'third',
        },
        {
          id: 28,
          label:
                   'CVCC DNS_1:\nCVCC strategy,\n-process, and\n-preparation of\ncustomer\nengagement',
          group: 'third',
        },
        {
          id: 29,
          label: 'CVCC DNS_2:\nBusiness Model\nInnovation',
          group: 'third',
        },
        {
          id: 30,
          label: 'Ecosyatems',
          group: 'third',
        },
        {
          id: 31,
          label: 'CVCC\nWorkshop',
          group: 'third',
        },
      ],
      edges: [
               { from: 21, to: 27 },
               { from: 21, to: 28 },
               { from: 21, to: 29 },
               { from: 21, to: 30 },
               { from: 21, to: 31 },
      ],
      opened: false,
    },
           {},
           {},
    {
      nodes: [
        {
          id: 24,
          label: 'Leading your\nDigital\nBusiness\nTransformation',
          group: 'second',
          size: 35,
        },
        {
          id: 32,
          label: 'Digital\nBusiness',
          group: 'third',
        },
        {
          id: 33,
          label: 'Digital\nLeadership\n/ Transformation',
          group: 'third',
        },
        {
          id: 34,
          label: 'LDBT\nWorkshop',
          group: 'third',
        },
      ],
      edges: [{ from: 24, to: 32 }, { from: 24, to: 33 }, { from: 24, to: 34 }],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 26,
          label: 'Business\nModel\nInnovation',
          group: 'second',
          size: 35,
        },
        {
          id: 35,
          label: 'Value\nProposition\nDesign (VPD)',
          group: 'third',
        },
        {
          id: 36,
          label: 'Business\nModelling\nbased on\nBizMo TM\n(BizMo)',
          group: 'third',
        },
        {
          id: 37,
          label: 'Ecosystems',
          group: 'third',
        },
        {
          id: 38,
          label: 'CVC\nWorkshop',
          group: 'third',
        },
      ],
      edges: [
               { from: 26, to: 35 },
               { from: 26, to: 36 },
               { from: 26, to: 37 },
               { from: 26, to: 38 },
      ],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 28,
          label:
                   'CVCC DNS_1:\nCVCC strategy,\n-process, and\n-preparation of\ncustomer\nengagement',
          group: 'third',
          size: 35,
        },
        {
          id: 39,
          label: 'CVCC -\nintrodction',
          group: 'fourth',
        },
        {
          id: 40,
          label: 'CVCC -\nenvironment',
          group: 'fourth',
        },
        {
          id: 41,
          label: 'CVCC - process\n& strategy',
          group: 'fourth',
        },
        {
          id: 42,
          label: 'CVCC - prepare\ncustomer\nengagement',
          group: 'fourth',
        },
      ],
      edges: [
               { from: 28, to: 39 },
               { from: 28, to: 40 },
               { from: 28, to: 41 },
               { from: 28, to: 42 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 29,
          label: 'CVCC DNS_2:\nBusiness Model\nInnovation',
          group: 'third',
          size: 35,
        },
        {
          id: 43,
          label: 'Value\nProposition\nDesign (VPD)',
          group: 'fourth',
        },
        {
          id: 44,
          label: 'Business\nModelling\nbased on\nBizMo TM\n(BizMo)',
          group: 'fourth',
        },
      ],
      edges: [{ from: 29, to: 43 }, { from: 29, to: 44 }],
      opened: false,
    },
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
  ],
  lex_auth_0128552176426270725: [
    {
      nodes: [
        {
          id: 0,
          label: '',
          group: 'first',
          widthConstraint: { minimum: 100 },
          x: -100,
          y: -50,
          shape: 'circularImage',
          size: 60,
          image: '/assets/common/learning-path/sales.png',
        },
        {
          id: 1,
          label: 'Sie Sales',
          group: 'second',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 2,
          label: 'Digi basics\nfor Sales',
          group: 'second',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 3,
          label: 'Sales\nLearning',
          group: 'second',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 4,
          label: 'Own your\ngrowth in\nSales & KAM',
          group: 'second',
          shape: 'circularImage',
          size: 40,
          image: '/assets/common/learning-path/11.png',
        },
      ],
      edges: [
               { from: 0, to: 1 },
               { from: 0, to: 2 },
               { from: 0, to: 3 },
               { from: 0, to: 4 },
      ],
      opened: true,
    },
    {
      nodes: [
        {
          id: 1,
          label: 'Sie Sales',
          group: 'second',
          shape: 'circularImage',
          size: 45,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 29,
          label: 'Get Tips\n& Tricks',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 30,
          label: 'Get\nKnowledge',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 31,
          label: 'Get\nReady',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/3.png',
        },
      ],
      edges: [{ from: 1, to: 29 }, { from: 1, to: 30 }, { from: 1, to: 31 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 2,
          label: 'Digi basics\nfor Sales',
          group: 'second',
          shape: 'circularImage',
          size: 45,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 32,
          label: 'Know your\ndigitalnenvironment',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 33,
          label: 'Digital\nSocial\nSelling – shape\nyour digital\npersona',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 34,
          label: 'Digital Social\nSelling – get\nin contact\nwith your\ncustomer',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 35,
          label: 'Digital\nTechnologies\nfor Sales',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/11.png',
        },
        {
          id: 36,
          label: 'Division specific\ntraining on\ndigitalization',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/12.png',
        },
      ],
      edges: [
               { from: 2, to: 32 },
               { from: 2, to: 33 },
               { from: 2, to: 34 },
               { from: 2, to: 35 },
               { from: 2, to: 36 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 3,
          label: 'Sales\nLearning',
          group: 'second',
          shape: 'circularImage',
          size: 45,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 37,
          label: 'Selling\nMethods',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 38,
          label: 'Portfolio',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 39,
          label: 'Business Specific',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 40,
          label: 'Vertical Markets',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/11.png',
        },
        {
          id: 41,
          label: 'Digitalization@Sales',
          shape: 'circularImage',
          group: 'third',
          size: 35,
          image: '/assets/common/learning-path/12.png',
        },
      ],
      edges: [
               { from: 3, to: 37 },
               { from: 3, to: 38 },
               { from: 3, to: 39 },
               { from: 3, to: 40 },
               { from: 3, to: 41 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 4,
          label: 'Own your\ngrowth in\nSales & KAM',
          group: 'second',
          shape: 'circularImage',
          size: 45,
          image: '/assets/common/learning-path/11.png',
        },
        {
          id: 5,
          label: 'Whats New?',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/1.jpg',
        },
        {
          id: 6,
          label: 'Competencies',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 7,
          label: 'Quick\nLinks',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 8,
          label: 'My Role\nin Sales',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/12.png',
        },
        {
          id: 9,
          label: 'My Role\nas a KAM',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/13.png',
        },
        {
          id: 10,
          label: 'Certification',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/14.png',
        },
        {
          id: 11,
          label: 'Selling Methods',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/CDP-Img.jpg',
        },
      ],
      edges: [
               { from: 4, to: 5 },
               { from: 4, to: 6 },
               { from: 4, to: 7 },
               { from: 4, to: 8 },
               { from: 4, to: 9 },
               { from: 4, to: 10 },
               { from: 4, to: 11 },
      ],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 6,
          label: 'Competencies',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/2.png',
        },
        {
          id: 12,
          label: 'Interpersonal &\nPersonal',
          group: 'fourth',
        },
        {
          id: 13,
          label: 'Functions &\n Methods',
          group: 'fourth',
        },
      ],
      edges: [{ from: 6, to: 12 }, { from: 6, to: 13 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 7,
          label: 'Quick\nLinks',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/3.png',
        },
        {
          id: 14,
          label: 'Sie Sales\nJob Profile\nPlatform',
          group: 'fourth',
        },
        {
          id: 15,
          label: 'GLC',
          group: 'fourth',
        },
      ],
      edges: [{ from: 7, to: 14 }, { from: 7, to: 15 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 8,
          label: 'My Role\nin Sales',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/12.png',
        },
        {
          id: 16,
          label: 'General\nSales',
          group: 'fourth',
        },
        {
          id: 17,
          label: 'Sales\nConsulting',
          group: 'fourth',
        },
        {
          id: 18,
          label: 'Sales Support\nand Admin',
          group: 'fourth',
        },
      ],
      edges: [{ from: 8, to: 16 }, { from: 8, to: 17 }, { from: 8, to: 18 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 9,
          label: 'My Role\nas a KAM',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/13.png',
        },
        {
          id: 19,
          label: 'Global\nKAM',
          group: 'fourth',
        },
        {
          id: 20,
          label: 'Regional\nKAM',
          group: 'fourth',
        },
        {
          id: 21,
          label: 'Certification',
          group: 'fourth',
        },
        {
          id: 22,
          label: 'Corporate\nKAM',
          group: 'fourth',
        },
      ],
      edges: [
               { from: 9, to: 19 },
               { from: 9, to: 20 },
               { from: 9, to: 21 },
               { from: 9, to: 22 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 10,
          label: 'Certification',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/14.png',
        },
        {
          id: 23,
          label: 'Sales\nExcellence',
          group: 'fourth',
        },
        {
          id: 24,
          label: 'OCA',
          group: 'fourth',
        },
      ],
      edges: [{ from: 10, to: 23 }, { from: 10, to: 24 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 11,
          label: 'Selling Methods',
          group: 'third',
          shape: 'circularImage',
          size: 35,
          image: '/assets/common/learning-path/CDP-Img.jpg',
        },
        {
          id: 25,
          label: 'Consulative\nSelling',
          group: 'fourth',
        },
        {
          id: 26,
          label: 'Technical\nSelling',
          group: 'fourth',
        },
        {
          id: 27,
          label: 'Value\nSelling',
          group: 'fourth',
        },
        {
          id: 28,
          label: 'Value Co\nCreation',
          group: 'fourth',
        },
      ],
      edges: [
               { from: 11, to: 25 },
               { from: 11, to: 26 },
               { from: 11, to: 27 },
               { from: 11, to: 28 },
      ],
      opened: false,
    },
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
    {
      nodes: [
        {
          id: 25,
          label: 'Consulative\nSelling',
          group: 'fourth',
        },
        {
          id: 42,
          label: 'The\nChallengerSale',
          group: 'fifth',
        },
      ],
      edges: [{ from: 25, to: 42 }],
      opened: false,
    },
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
           {},
  ],
  lex_auth_01285522520727552015: [
    {
      nodes: [
        {
          id: 0,
          label: 'New Work',
          group: 'center',
          shape: 'circularImage',
          image:
                   '/assets/common/learning-path/sketch-on-tablet_iStock-1141040803_1-col-entry.jpg',
          color: 'gray',
          size: 50,
        },
        {
          id: 1,
          label: 'MyNextWork',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/1.jpg',
          size: 40,
        },
        {
          id: 2,
          label: 'NextWork',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/2.png',
          size: 40,
        },
        {
          id: 3,
          label: 'New Work\nNew Culture',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/3.png',
          size: 40,
        },
        {
          id: 4,
          label: 'Tools',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/11.png',
          size: 40,
        },
      ],
      edges: [
               { from: 0, to: 1 },
               { from: 0, to: 2 },
               { from: 0, to: 3 },
               { from: 0, to: 4 },
      ],
      opened: true,
    },
    {
      nodes: [
        {
          id: 1,
          label: 'MyNextWork',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/1.jpg',
          size: 40,
        },
        {
          id: 5,
          label: 'Leadership',
          group: 'digiGen',
        },
        {
          id: 6,
          label: 'Product Business',
          group: 'digiGen',
        },
        {
          id: 7,
          label: 'Manufacturing',
          group: 'digiGen',
        },
        {
          id: 8,
          label: 'Solution Business,\nEngineering, pm@siemens',
          group: 'digiGen',
        },
        {
          id: 9,
          label: 'SDS',
          group: 'digiGen',
        },
        {
          id: 10,
          label: 'Support Functions',
          group: 'digiGen',
        },
      ],
      edges: [
               { from: 1, to: 5 },
               { from: 1, to: 6 },
               { from: 1, to: 7 },
               { from: 1, to: 8 },
               { from: 1, to: 9 },
               { from: 1, to: 10 },
      ],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 3,
          label: 'New Work\nNew Culture',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/3.png',
          size: 40,
        },
        {
          id: 11,
          label: 'Agile Mindset',
          group: 'digiTek',
        },
        {
          id: 12,
          label: 'Agile Organisation',
          group: 'digiTek',
        },
        {
          id: 13,
          label: 'Agile Cosmos',
          group: 'digiTek',
        },
      ],
      edges: [{ from: 3, to: 11 }, { from: 3, to: 12 }, { from: 3, to: 13 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 4,
          label: 'Tools',
          group: 'first',
          shape: 'circularImage',
          image: '/assets/common/learning-path/11.png',
          size: 40,
        },
        {
          id: 14,
          label: 'Agile/Lean Methods',
          group: 'digiMgm',
        },
        {
          id: 15,
          label: 'Collaboration Tools',
          group: 'digiMgm',
        },
      ],
      edges: [{ from: 4, to: 14 }, { from: 4, to: 15 }],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 6,
          label: 'Product Business',
          group: 'digiGen',
        },
        {
          id: 16,
          label: 'Product Owner',
          group: 'third',
        },
        {
          id: 17,
          label: 'Scrum Master',
          group: 'third',
        },
        {
          id: 18,
          label: 'R&D PM',
          group: 'third',
        },
      ],
      edges: [{ from: 6, to: 16 }, { from: 6, to: 17 }, { from: 6, to: 18 }],
      opened: false,
    },
           {},
           {},
           {},
    {
      nodes: [
        {
          id: 10,
          label: 'Support Functions',
          group: 'digiGen',
        },
        {
          id: 19,
          label: 'BA',
          group: 'third',
        },
        {
          id: 20,
          label: 'HR',
          group: 'third',
        },
        {
          id: 21,
          label: 'SCM',
          group: 'third',
        },
      ],
      edges: [{ from: 10, to: 19 }, { from: 10, to: 20 }, { from: 10, to: 21 }],
      opened: false,
    },
    {
      nodes: [
        {
          id: 11,
          label: 'Agile Mindset',
          group: 'digiTek',
        },
        {
          id: 22,
          label: 'Mindset',
          group: 'third',
        },
        {
          id: 23,
          label: 'Focus on\ncustomer value',
          group: 'third',
        },
        {
          id: 24,
          label: 'Eliminate waste',
          group: 'third',
        },
        {
          id: 25,
          label: 'Optimize the\nentire value stream',
          group: 'third',
        },
        {
          id: 26,
          label: 'Pull and Flow',
          group: 'third',
        },
        {
          id: 27,
          label: 'Learn fast - Deliver\nfast and create knowledge',
          group: 'third',
        },
        {
          id: 28,
          label: 'Self organizing teams',
          group: 'third',
        },
        {
          id: 29,
          label: 'Go and see',
          group: 'third',
        },
        {
          id: 30,
          label: 'Eliminate waste',
          group: 'third',
        },
        {
          id: 31,
          label: 'Build quality from\nthe beginning',
          group: 'third',
        },
        {
          id: 32,
          label: 'The Flow Framework',
          group: 'third',
        },
      ],
      edges: [
               { from: 11, to: 22 },
               { from: 11, to: 23 },
               { from: 11, to: 24 },
               { from: 11, to: 25 },
               { from: 11, to: 26 },
               { from: 11, to: 27 },
               { from: 11, to: 28 },
               { from: 11, to: 29 },
               { from: 11, to: 30 },
               { from: 11, to: 31 },
               { from: 11, to: 32 },
      ],
      opened: false,
    },
    {
      nodes: [
        {
          id: 12,
          label: 'Agile Organisation',
          group: 'digiTek',
        },
        {
          id: 33,
          label: 'Self organizing teams',
          group: 'third',
        },
      ],
      edges: [{ from: 12, to: 33 }],
      opened: false,
    },
           {},
    {
      nodes: [
        {
          id: 14,
          label: 'Agile/Lean Methods',
          group: 'digiMgm',
        },
        {
          id: 34,
          label: 'Hoshin Kanri',
          group: 'third',
        },
        {
          id: 35,
          label: 'Retrospective',
          group: 'third',
        },
        {
          id: 36,
          label: 'Ranked Backlog',
          group: 'third',
        },
        {
          id: 37,
          label: 'Time Boxed Development',
          group: 'third',
        },
        {
          id: 38,
          label: 'Kanban',
          group: 'third',
        },
        {
          id: 39,
          label: 'Crossfunctional Teams',
          group: 'third',
        },
        {
          id: 40,
          label: 'Visual Management',
          group: 'third',
        },
        {
          id: 41,
          label: 'Daily Standup',
          group: 'third',
        },
        {
          id: 42,
          label: 'Value stream Mapping',
          group: 'third',
        },
        {
          id: 43,
          label: 'Gemba Walk',
          group: 'third',
        },
        {
          id: 44,
          label: 'Scrum',
          group: 'third',
        },
        {
          id: 45,
          label: 'MVP/MMP',
          group: 'third',
        },
        {
          id: 46,
          label: 'Structured Problem Solving',
          group: 'third',
        },
        {
          id: 47,
          label: 'Value effort matrix',
          group: 'third',
        },
        {
          id: 48,
          label: 'Design Thinking',
          group: 'third',
        },
      ],
      edges: [
               { from: 14, to: 34 },
               { from: 14, to: 35 },
               { from: 14, to: 36 },
               { from: 14, to: 37 },
               { from: 14, to: 38 },
               { from: 14, to: 39 },
               { from: 14, to: 40 },
               { from: 14, to: 41 },
               { from: 14, to: 42 },
               { from: 14, to: 43 },
               { from: 14, to: 44 },
               { from: 14, to: 45 },
               { from: 14, to: 46 },
               { from: 14, to: 47 },
               { from: 14, to: 48 },
      ],
      opened: false,
    },
           {},
  ],
}

export const salesData: { [key: string]: IDynamicDataContent[] } = {
  'Value Selling': [
    {
      name: 'What is CPV?',
      type: 'videocam',
      description: 'You should set the price according to the value for the consumers.',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
      completed: true,
    },
    {
      name: 'Improving your understanding of your prospect\'s situation',
      type: 'web',
      description: 'Collect important background information from potential customers.',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 2,
      tags: '',
      completed: true,
    },
    {
      name: 'Understanding value creation for your customers',
      type: 'videocam',
      description: 'Value Selling helps the Sales Reps to differentiate from their competitors.',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
      completed: true,
    },
    {
      name: 'Negotiating Sales',
      type: 'web',
      description:
        'Does it only happen at the end of the sale, or is it an ongoing conversation through the entire process?',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 5,
      tags: '',
      completed: false,
    },
    {
      name: 'How to sell your value and your price',
      type: 'videocam',
      description:
        'In this handbook you will find numerous answers to this question: \'What should I do in front of a customer?',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 2,
      tags: '',
      completed: false,
    },
    {
      name: 'Value Selling - Winning complex Business Opportunities',
      type: 'web',
      description: 'A training for Sales representatives and sales teams.',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 5,
      tags: '',
      completed: false,
    },
  ],
  'General Sales': [
    {
      name: 'Sales Representative Learning Program',
      type: 'videocam',
      description:
        'Penetrating the market, cultivating accounts and seizing business opportunities',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
    },
    {
      name: 'Senior Sales Representative Learning Program (SP2)',
      type: 'web',
      description:
        'Achieving excellence in sales, mastering complex change in challenging and dynamic market environments',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 2,
      tags: '',
    },
    {
      name: 'Sales Management Learning Program',
      type: 'videocam',
      description:
        'Connecting with customers, managing a business, coaching sales teams, winning in-house support',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
    },
    {
      name: 'How to sell your value and your price',
      type: 'web',
      description: 'What is a good sales conversation?',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 5,
      tags: '',
    },
  ],
  'Interpersonal & Personal': [
    {
      name: 'High-impact interpersonal skills',
      type: 'videocam',
      description: 'How to be a persuasive leader',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
    },
    {
      name: 'Presenting an effective message',
      type: 'web',
      description: 'Master the art of making a great impression',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 2,
      tags: '',
    },
    {
      name: '3 strategies business presenters can learn from stage performers',
      type: 'videocam',
      description: 'Some simple suggestions to improve your next speech',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 5,
      tags: '',
    },
    {
      name: 'Communication with impact: Storytelling',
      type: 'web',
      description:
        'How can you make your presentation more engaging? Storytelling is a way to do so!',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 5,
      tags: '',
    },
  ],
  'WHats New?': [],
  'Get Knowledge': [
    {
      name: 'What is CPV?',
      type: 'videocam',
      description:
        'Get a first look into SieSales brought to you by Salesforce4Siemens (Awareness Video)',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 252,
      tags: '#get knowledge#siesales',
    },
    {
      name: 'Learn more about SieSales & get prepared!',
      type: 'web',
      description: 'SieSales - Web-Based Training',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 762,
      tags: '#get knowledge#siesales',
    },
    {
      name: 'See SieSales functionalities and innovations live in action!',
      type: 'videocam',
      description: 'Learn more by watching the SieSales Tutorials',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 215,
      tags: '#get knowledge#siesales',
    },
    {
      name: 'What is the #Salesforce4Siemens Project about?',
      type: 'web',
      description:
        'Get insights and an understanding of how the Salesforce4Siemens project is set up!',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 24,
      tags: '#get knowledge#siesales',
    },
  ],
  'Value Proposition Design (VPD)': [
    {
      name: 'General overview VPD, BizMo, Validation',
      type: 'videocam',
      description: 'Overview of the Siemens BIZMO Framework for new business generation',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags:
        '#digital business, #bizmo, # business model, #value proposition, #user profile map, #value proposition, #jobs-to-be-done',
    },
    {
      name: 'Buying Center / Persona',
      type: 'web',
      description: 'A deeper look into how buying decisions are taken',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#buyingcenter, #persona',
    },
    {
      name: 'Introducing Vendix',
      type: 'videocam',
      description: 'Applying BIZMO: A case study',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'Vendixx #Syla.#casestudy #buyingcenter, #persona #job2bdone',
    },
    {
      name: 'Introducing Value Proposition Design (VPD)',
      type: 'web',
      description: 'Creating value by walking in the customer\'s shoes',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#UPM, #VPM #VPD #ValueProposition',
    },
    {
      name: 'Deep dive Value Proposition Design (VPD)',
      type: 'videocam',
      description: 'A deeper look into the various elements of Value Proposition Design',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#UPM, #VPM #VPD #ValueProposition',
    },
    {
      name: 'Example Value Proposition Design (VPD) - Vendixx',
      type: 'web',
      description: 'Case Study: Let\'s create value for Syla.',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: 'Vendixx #Syla.#casestudy #userprofilemap #UPM, #VPM #job2bdone',
    },
  ],
  'CVCC - introdction': [
    {
      name: 'Why CVCC? ',
      type: 'videocam',
      description: 'Understanding the reasons why CVCC is a new and innovative sales approach',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#CVCC #Sales approach',
    },
    {
      name: 'How CVCC?',
      type: 'web',
      description: 'How to conduct a CVCC endeavor',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#CVCC #Sales approach',
    },
    {
      name: 'What CVCC?',
      type: 'videocam',
      description: 'What is CVCC',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#CVCC #Sales approach',
    },
    {
      name: 'Expert interview: Assem Khalaili?',
      type: 'web',
      description: 'Meet the inventor of the CVCC concept at Siemens',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#CVCC #Sales approach',
    },
  ],
  'CVCC - environment': [
    {
      name: 'Siemens Process Excellence - how do we work',
      type: 'videocam',
      description: 'How does Siemens as a company work',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#SiPEX #process #valuechain #SCM #PLM #CRM',
    },
    {
      name: 'Business types @Siemens - Product-, Service-, Plant-/Solution-Business',
      type: 'web',
      description: 'What are the business types we are deploying at Siemens',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags:
        '#Business-types #Product-business #Project-business #Solution-business # Service-business #PM@Siemens',
    },
    {
      name: 'VUCA / Stacey => explore vs. exploit',
      type: 'videocam',
      description: 'When do we need to execute and when do we need to experiment?',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#stacey-matrix #complex # complicated #VUCA #whattobuild # howtobuild',
    },
    {
      name: 'Different Sales approaches and when to use them',
      type: 'web',
      description: 'How to differentiate the sales approaches at Siemens',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#CVCC #Consultative Selling #Value Selling #Value based selling #Technical selling ',
    },
  ],
  'CVCC - process & strategy': [
    {
      name: 'CVCC - framework / overview',
      type: 'videocam',
      description: 'What are the elements of CVCC',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#CVCC framework',
    },
    {
      name: 'CVCC - framework / legal implications',
      type: 'web',
      description: 'When to involve legal in CVCC',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags:
        '#CVCC framework #legal touchpoints #NDA #Cooperation agreement #Joint development agreememt',
    },
    {
      name: 'CVCC - resource requirements',
      type: 'videocam',
      description: 'Preparing the strategic setup for CVCC an allocating the needed requirements',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#set strategy #CVCC resources',
    },
    {
      name: 'CVCC - customer selection',
      type: 'web',
      description: 'How to select the right customers for CVCC',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#customer selection #selection criteria #selection matrix #CVCC customers',
    },
  ],
  'CVCC - prepare customer engagement': [
    {
      name: 'CVCC: Insight preparation workshop - whiteboarding',
      type: 'videocam',
      description: 'Analyzing the market environment of the customer deriving key challenges',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags:
        '#discovery whiteboard #customer challenges #market drivers #customer objectives #customer KPIs',
    },
    {
      name: 'CVCC: How to sell a discovery session - 5 steps of selling',
      type: 'web',
      description: 'A dialetic approach to convincing customers to enter into a CVCC endeavor',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#convincing method #5 steps of selling',
    },
    {
      name: 'CVCC: Customer discovery session',
      type: 'videocam',
      description:
        'Jointly with the customer analyzing potentials for CVCC to improve their business',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#discovery session #customer discovery session #question tree #discvovery tree',
    },
  ],
  'Business Modelling based on BizMo TM (BizMo)': [
    {
      name: 'Connection between VPD and BizMo',
      type: 'videocam',
      description: 'how to turn customer value into revenue',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD',
    },
    {
      name: 'Introducing BizMo',
      type: 'web',
      description: 'The Canvas for new business models',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD #Frontstage #backstage',
    },
    {
      name: 'BizMo: front stage',
      type: 'videocam',
      description: 'How to describe customer interaction  in the Canvas',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD #Frontstage #revenuemodule',
    },
    {
      name: 'BizMo: revenue module',
      type: 'web',
      description: 'A deeper look into the various ways to generate revenue',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD #Frontstage #revenuemodule #PIM #pricinginnovationmodel',
    },
    {
      name: 'BizMo: back stage',
      type: 'videocam',
      description: 'A thorough look into  the engine room of a new business',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#makeorbuy, #backstage #costdriver #canvas #backstage',
    },
    {
      name: 'Example BizMo - Vending Machine Industry',
      type: 'web',
      description: 'Back to our case study: How Vendix turned Value into profit',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'Vendixx #Syla. #casestudy ##Frontstage #backstage',
    },
  ],
  Ecosystems: [
    {
      name: 'Eco Basics',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Eco & PLM RnD',
      type: 'web',
      description: '',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Eco & Marketing Sales',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Eco & Quality Management',
      type: 'web',
      description: '',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Eco & BA',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Why do we need ecosystems?',
      type: 'web',
      description: '',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
  ],
  'Digital Business': [
    {
      name: 'General overview VPD, BizMo, Validation',
      type: 'videocam',
      description: 'Overview of the Siemens BIZMO Framework for new business generation',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags:
        '#digital business, #bizmo, # business model, #value proposition, #user profile map, #value proposition, #jobs-to-be-done',
    },
    {
      name: 'Buying Center / Persona',
      type: 'web',
      description: 'A deeper look into how buying decisions are taken',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#buyingcenter, #persona ',
    },
    {
      name: 'Introducing Vendix',
      type: 'videocam',
      description: 'Applying BIZMO: A case study',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'Vendixx #Syla. #casestudy #buyingcenter, #persona #job2bdone',
    },
    {
      name: 'Introducing Value Proposition Design (VPD)',
      type: 'web',
      description: 'Creating value by walking in the customer\'s shoes',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#UPM, #VPM #VPD #ValueProposition',
    },
    {
      name: 'Connection between VPD and BizMo',
      type: 'videocam',
      description: 'how to turn customer value into revenue',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD',
    },
    {
      name: 'Introducing BizMo',
      type: 'web',
      description: 'The Canvas for new business models',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '#Canvas, #BIZMO, #VPD #Frontstage #backstage',
    },
    {
      name: 'Scrum',
      type: 'videocam',
      description:
        'Scrum is a lightweight, iterative and incremental framework for managing projects in complex environments',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'scrum, agile, project, iterative, leadership, self-steering',
    },
    {
      name: 'The economic essentials of digital strategy',
      type: 'web',
      description: '',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Siemens working group - Business Models for Digital Services',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
  ],
  'Digital Leadership / Transformation': [
    {
      name: 'LFW Agile Cosmos',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Agile Development - World of R&D',
      type: 'web',
      description:
        'This wiki was designed for our R&D community. But it also contains a lot of methods and',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Unlocking success in digital transformations',
      type: 'videocam',
      description: '',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: '',
    },
    {
      name: 'Pattform Industrie 4.0',
      type: 'web',
      description: 'Central network for driving forward digitalization in manufacturing.',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: '',
    },
  ],
  'Digi Finance': [
    {
      name: 'Finance Innovation Lab',
      type: 'videocam',
      description:
        'Finance Innovation Lab is the starting page for different aspects of innovations which.',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'BI, business intelligence, visual analytics, digitalfinance',
    },
    {
      name: 'reportingimpulse Academy -Visual Data Analytics',
      type: 'web',
      description: 'We help you to get closer to your goal of a data-driven company!',
      imageUrl: '/assets/common/learning-path/DLP-Img.jpg',
      views: 0,
      tags: 'BI, business intelligence, visual analytics, digitalfinance',
    },
    {
      name: 'fit - Digitalization in Finance',
      type: 'videocam',
      description:
        'financeTrainings are YOUR trustful source for financial knowledge right out of Finance.',
      imageUrl: '/assets/common/learning-path/CDP-Img.jpg',
      views: 0,
      tags: 'BI, business intelligence, visual analytics, digitalfinance',
    },
  ],
}
