/*
 * Public API Surface of app
 */

// module exports
export * from './lib/routes/account-settings/account-settings.module'
export * from './lib/routes/app-setup/app-setup.module'
export * from './lib/routes/app-toc/app-toc.module'
export * from './lib/routes/channels/channels.module'
export * from './lib/routes/concept-graph/concept-graph.module'
export * from './lib/routes/content-assignment/content-assignment.module'
export * from './lib/routes/calendar/calendar.module'
export * from './lib/routes/feedback-v2/feedback-v2.module'
export * from './lib/routes/feedback/feedback.module'
export * from './lib/routes/goals/goals.module'
export * from './lib/routes/info/info.module'
export * from './lib/routes/infy/infy.module'
export * from './lib/routes/knowledge-board/knowledge-board.module'
export * from './lib/routes/leaderboard/leaderboard.module'
export * from './lib/routes/academy-learning-paths/academy-learning-paths.module'
export * from './lib/routes/infosysagm/infosysagm.module'
export * from './lib/routes/learning-path/learning-path.module'
export * from './lib/routes/my-dashboard/my-dashboard.module'
export * from './lib/routes/my-learning/my-learning.module'
export * from './lib/routes/my-rewards/my-rewards.module'
export * from './lib/routes/notification-v2/notification-v2.module'
export * from './lib/routes/notification/notification.module'
export * from './lib/routes/playlist/playlist.module'
export * from './lib/routes/profile/profile.module'
export * from './lib/routes/search/search.module'
export * from './lib/routes/skill-management/skill-management.module'
export * from './lib/routes/social/social.module'
export * from './lib/routes/app-event/app-event.module'
