### Default variable file for lms-service ###

namespace: dev
imagepullsecrets: devregistrysecret
dockerhub: eagle-docker.tarento.com


env:
  javaoptions: -Xmx600m

replicaCount: 1
repository: projecx-frac-service
image_tag: 7cb4218
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 8095
  targetport: 8095
strategy:
  type: RollingUpdate
  maxsurge: 25%
  maxunavailable: 25%

